// DO NOT EDIT!
// Csharp generated by Buffman 💪
// Versions:
//		Buffman: 0.0.1
//		Flatc: v25.2.10
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace common
{

public enum Status : int
{
  STATUS_UNKNOWN = 0,
  STATUS_ACTIVE = 1,
  STATUS_INACTIVE = 2,
  STATUS_PENDING = 3,
  STATUS_SUSPENDED = 4,
};


}
