// DO NOT EDIT!
// Ts generated by Buffman 💪
// Versions:
//		Buffman: 0.0.1
//		Flatc: v25.2.10

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

export enum Status {
  STATUS_UNKNOWN = 0,
  STATUS_ACTIVE = 1,
  STATUS_INACTIVE = 2,
  STATUS_PENDING = 3,
  STATUS_SUSPENDED = 4
}
