// automatically generated by the FlatBuffers compiler, do not modify

package services

@Suppress("unused")
class NotificationType private constructor() {
    companion object {
        const val NOTIFICATION_TYPE_UNKNOWN: Int = 0
        const val NOTIFICATION_TYPE_EMAIL: Int = 1
        const val NOTIFICATION_TYPE_SMS: Int = 2
        const val NOTIFICATION_TYPE_PUSH: Int = 3
        const val NOTIFICATION_TYPE_IN_APP: Int = 4
    }
}
