// automatically generated by the FlatBuffers compiler, do not modify

package services

@Suppress("unused")
class Priority private constructor() {
    companion object {
        const val PRIORITY_LOW: Int = 0
        const val PRIORITY_MEDIUM: Int = 1
        const val PRIORITY_HIGH: Int = 2
        const val PRIORITY_URGENT: Int = 3
    }
}
