// DO NOT EDIT!
// Kotlin files generated by Buffman 💪.
// Versions:
//		Buffman: 0.0.1
// 		Flatc: 25.2.10

package services

@Suppress("unused")
class Priority private constructor() {
    companion object {
        const val PRIORITY_LOW: Int = 0
        const val PRIORITY_MEDIUM: Int = 1
        const val PRIORITY_HIGH: Int = 2
        const val PRIORITY_URGENT: Int = 3
    }
}
