// DO NOT EDIT!
// Ts generated by Buffman 💪
// Versions:
//		Buffman: 0.0.1
//		Flatc: v25.2.10

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

export { MetadataEntry } from './send-notification-request-/metadata-entry.js';
