// automatically generated by the FlatBuffers compiler, do not modify

package common

@Suppress("unused")
class Status private constructor() {
    companion object {
        const val STATUS_UNKNOWN: Int = 0
        const val STATUS_ACTIVE: Int = 1
        const val STATUS_INACTIVE: Int = 2
        const val STATUS_PENDING: Int = 3
        const val STATUS_SUSPENDED: Int = 4
    }
}
