package generator

import (
	"os"
	"strings"

	"github.com/machanirobotics/buffman/internal"
	"github.com/machanirobotics/buffman/pkg/template"
)

var msg = `// DO NOT EDIT!
// %s files generated by Buffman 💪.
// Versions:
//		Buffman: %s
// 		Flatc: %s
`
var comment = template.NewTemplate(msg)

func (f *FlatGenerator) insertGeneratedComments(language, langFilePath string) error {
	// Read the entire file content
	content, err := os.ReadFile(langFilePath)
	if err != nil {
		return err
	}

	// Convert to string and split into lines
	lines := strings.Split(string(content), "\n")

	// Remove the first line if there are any lines
	if len(lines) > 0 {
		lines = lines[1:]
	}

	// Prepare the comment to prepend
	commentStr := comment.Format(language, internal.Version, internal.GetFlatCVersion())

	// Join remaining lines back together
	remainingContent := strings.Join(lines, "\n")

	// Create new content: comment + remaining content (without first line)
	newContent := commentStr + remainingContent

	// Write the new content back to the file
	err = os.WriteFile(langFilePath, []byte(newContent), 0644)
	if err != nil {
		return err
	}

	return nil
}
