// automatically generated by the FlatBuffers compiler, do not modify

package com.fb.services;

@SuppressWarnings("unused")
public final class Priority {
  private Priority() { }
  public static final int PRIORITY_LOW = 0;
  public static final int PRIORITY_MEDIUM = 1;
  public static final int PRIORITY_HIGH = 2;
  public static final int PRIORITY_URGENT = 3;

  public static final String[] names = { "PRIORITY_LOW", "PRIORITY_MEDIUM", "PRIORITY_HIGH", "PRIORITY_URGENT", };

  public static String name(int e) { return names[e]; }
}

