package template

import (
	"fmt"
	"strings"

	"github.com/machanirobotics/buffman/internal"
	"github.com/machanirobotics/buffman/internal/install"
)

// Template holds version information and comment generation
type Template struct {
	languagePrefix string
	flatC          string
	buffman        string
}

// NewTemplate creates a new Template instance
func NewTemplate(languagePrefix string) (*Template, error) {
	installer := install.NewManager()
	installer.RegisterInstaller(install.FlatbuffersInstaller, install.NewInstaller(install.FlatbuffersInstaller))
	flatc := installer.GetInstaller(install.FlatbuffersInstaller)
	version, err := flatc.GetVersion()
	if err != nil {
		return nil, err
	}
	return &Template{
		languagePrefix: languagePrefix,
		flatC:          version,
		buffman:        internal.Version,
	}, nil
}

// BuildDefaultComment generates the standard header comment
func (t *Template) BuildDefaultComment(language string) string {
	var builder strings.Builder

	builder.WriteString(t.languagePrefix + " DO NOT EDIT!\n")
	builder.WriteString(fmt.Sprintf("%s %s generated by Buffman 💪\n", t.languagePrefix, language))
	builder.WriteString(fmt.Sprintf("%s Versions:\n", t.languagePrefix))
	builder.WriteString(fmt.Sprintf("%s\t\tBuffman: %s\n", t.languagePrefix, t.buffman))
	builder.WriteString(fmt.Sprintf("%s\t\tFlatc: v%s\n", t.languagePrefix, t.flatC))

	return builder.String()
}

// BuildCustomComment allows building comments with custom content
func (t *Template) BuildCustomComment(lines ...string) string {
	var builder strings.Builder

	for _, line := range lines {
		builder.WriteString(t.languagePrefix)
		builder.WriteString(" ")
		builder.WriteString(line)
		builder.WriteString("\n")
	}

	return builder.String()
}

// BuildCustomCommentf creates a single formatted comment line
func (t *Template) BuildCustomCommentf(format string, args ...interface{}) string {
	formattedLine := fmt.Sprintf(format, args...)
	return t.BuildCustomComment(formattedLine)
}

// GetVersionInfo returns version information as a map
func (t *Template) GetVersionInfo() map[string]string {
	return map[string]string{
		"buffman": t.buffman,
		"flatc":   t.flatC,
	}
}
